name: Build XCFramework

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14
    strategy:
      matrix:
        xcode-version: [15.4, 16.1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Xcode select ${{ matrix.xcode-version }}
        run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer'
      - name: Get Swift Version
        run: |
          SWIFT_MAJOR_VERSION=$(swift --version 2>&1 | awk '/Apple Swift version/ { split($7, ver, "."); print ver[1]; exit }')
          echo "Swift major version: $SWIFT_MAJOR_VERSION"
          echo "SWIFT_VERSION=$SWIFT_MAJOR_VERSION.0" >> "$GITHUB_ENV"
      - name: Build xcframework
        run: sh build.sh
        env:
          SWIFT_VERSION: ${{ env.SWIFT_VERSION }}
